### ISSUE TITLE
Memory leak inside context

### ISSUE THREAD

**Issue by nerzh** [tonlabs/ever-sdk#1006]
Hello dear team. You have a memory leak inside the ServerLink class initializer. Please fix this as there are large memory leaks every time a context is created. If you do not pass an array of endpoints when initializing the context, there is no memory leak.

Presumably the leak occurs in this section of code:

<img width="938" alt="Снимок экрана 2023-06-22 в 15 07 04" src="https://github.com/tonlabs/ever-sdk/assets/10519803/5ea73dd3-d5df-4670-8212-031090936894">

**Comment by cryshado** [comment]
Thanks! Fixed in #1009
