### ISSUE TITLE
OpenSSL 1.1.1 End of Life

### ISSUE THREAD

**Issue by ch1seL** [tonlabs/ever-sdk#1045]
[OpenSSL 1.1.1 has reached its EOL](https://www.openssl.org/blog/blog/2023/09/11/eol-111/), but the SDK still requires libssl1.1. Most modern OS distributions are built on OpenSSL 3, and we have to install an outdated library to use the SDK.

**Comment by bvscd** [comment]
Currently it's hard to provide binaries distribution for technical reasons. As a temporary workaround, it is possible to build core SDK library from source, and there should be no issue with OpenSSL version. Overall procedure is described in https://github.com/tonlabs/ever-sdk/blob/master/README.md. Short instruction is below.

Prerequisites: NodeJs (v14+), Rust (1.47+)

Build instructions:
cd <your-build_folder>
git clone https://github.com/tonlabs/ever-sdk.git
cd ever-sdk/ton_client
node build.js

Output binary path: ever-sdk/ton_client/bin (gzipped), ever-sdk/ton_client/build (uncompressed)
