### ISSUE TITLE
Build fails on target wasm32-unknown-emscripten

### ISSUE THREAD

**Issue by ch1seL** [tonlabs/ever-sdk#606]
I think it depends on: https://github.com/chronotope/chrono/issues/519
Let's close this issue after chrono package will be released with fix and all dependencies will be updated 😺

**Comment by ch1seL** [comment]
Oh, it seems like a few more packages are incompatible with this target 😢

**Comment by elasticLove1** [comment]
Can you please watch for the fix and notify us when they release it?

**Comment by elasticLove1** [comment]
> Oh, it seems like a few more packages are incompatible with this target 😢
If you find out how to fix them too, let us know:(

**Comment by ch1seL** [comment]
> @elasticLove1 I tried to build again and now everything is ok and we can close it. However, I would like to ask you to add building the Emscripten binary wasm artifact in you release pipeline 😄

Although no, it did not work in runtime, wasm-bindgen does not support wasm32-unknown-emscripten and is not going to https://rustwasm.github.io/wasm-bindgen/reference/rust-targets.html?highlight=wasm32-un#other-web- targets
