### ISSUE TITLE
AbiEvent type doesn't have outputs

### ISSUE THREAD

**Issue by cassandrus** [tonlabs/ever-sdk#911]
Description of [AbiEvent](https://github.com/tonlabs/ever-sdk/blob/master/docs/reference/types-and-methods/mod_abi.md#abievent) type in SDK
```
type AbiEvent = {
    name: string,
    inputs: AbiParam[],
    id?: string | null
}
```

Still, ABI files have `outputs` tag:
https://github.com/EverscaleGuild/everscale-contract-library/blob/main/solidity/safemultisig/SafeMultisigWallet.abi.json#L119

I understand that SafeMultisig is old and outputs are not needed, but it's strange that I can't parse ABI files (using strong typing) with your own types.

**Comment by elasticLove1** [comment]
We suggest to remove output section from multisig ABI. @cassandrus
